name: Dataset-Search-Tool
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/Dataset-Search-Tool
  original_url: https://huggingface.co/spaces/Chris4K/Dataset-Search-Tool

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:45:21
